### ISSUE TITLE
There is a typo on the front page

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cc-wp-theme#4]
The front page headline currently reads:
"We're helping to realize the full potential of the Internet—universal access to research and education, full participation in culture—to drive a new era of **development growth, and productivity."**

should read:

""We're helping to realize the full potential of the Internet—universal access to research and education, full participation in culture—to drive a new era of **development, growth, and productivity.""**

The list is missing a comma between the words development and growth.

**Comment by mattl** [comment]
https://github.com/creativecommons/cc-wp-theme/commit/f45676ba59bd478317da82084c095efc85ea36fa
